# PostgreSQL version 1.1.3
#   gem install pg

default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: pixdream_development

test:
  <<: *default
  database: pixdream_test

production:
  <<: *default
  database: pixdream_production
